CREATE OR REPLACE TRIGGER "READER_ID_TRG"
BEFORE INSERT ON "READER"
FOR EACH ROW
BEGIN
  IF :NEW."READER_ID" IS NULL THEN
    SELECT "READER_SEQ".NEXTVAL 
    INTO :NEW."READER_ID" 
    FROM DUAL;
  END IF;
END;
/